import type { Metadata } from "next";
import { Providers } from "./providers";
import SidebarNavigation from "@/components/shared/SidebarNavigation/SidebarNavigation";
import { Box, Flex, Show } from "@chakra-ui/react";
import AuthRedirectContainer from "@/components/features/auth/AuthRedirectContainer/AuthRedirectContainer";

export const metadata: Metadata = {
  title: "TV Shows App | React Course @ Infinum Academy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <AuthRedirectContainer />
          <Show above="md">
            <DesktopLayout>
              {children}
            </DesktopLayout>
          </Show>
          <Show below="md">
            <MobileLayout>
              {children}
            </MobileLayout>
          </Show>
        </Providers></body>
    </html>
  );
}

function DesktopLayout({children}: {children: React.ReactNode}) {
  return (
    <Flex>
      <SidebarNavigation />
      <Box flex='1' flexDir='row' minHeight="100vh">
        {children}
      </Box>
    </Flex>
  )
}

function MobileLayout({children}: {children: React.ReactNode}) {
  return (
    <Flex direction="column">
      <SidebarNavigation />
      <Box flex='1' flexDir='row' minHeight="100vh">
        {children}
      </Box>
    </Flex>
  )
}
